- name: installing needed libs
  apt:
    name: ca-certificates curl
    state: present
    update_cache: yes

- name: prepare GPG keys
  command: "sudo install -m 0755 -d /etc/apt/keyrings"

- name: downloading GPG keys
  command: "sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc"

- name: setting permissions
  command: "sudo chmod a+r /etc/apt/keyrings/docker.asc"

- name: Preparing apt repository
  shell: |
  echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: update repository
  apt:
    update_cache: yes
    